### Getting all the movies

GET http://Localhost:3000/movies?page=3&limit=5

### Getting a movie by its ID
GET http://Localhost:3000/movies/id/2147a25e-60da-11ef-8c0b-900f0c400779

### Getting movie by genre

GET http://Localhost:3000/movies/genre/Action

### Update a movie 
PATCH  http://Localhost:3000/movies/id/2147a25e-60da-11ef-8c0b-900f0c400779
Content-Type: application/json

{
    "title" : "Cry Bernabeu Cry",
    "director": "Joseph Guardiola",
    "rate": 7.6
}

### create a movie


POST http://Localhost:3000/movies
Content-Type: application/json

{
    "title": "A season in a row",
    "director": "M. Verstappen",
    "duration": 162,
    "genre": ["Action", "Drama"],
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrh6E9W2yRjT4-LXlMn8JucRtVYDHPjwWNAw&s"
}